// External imports
import Head from "next/head";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

// Internal imports
import { ArrowDrawing } from "@/components/Icon";
import Card from "@/components/Card";
import Tag from "@/components/Tag";

import companies from "@/data/companies";

export default function Home() {
  const [currentFilter, setCurrentFilter] = useState("All");

  let tagsArray = [];

  for (const company of companies) {
    for (const tag of company.tags) {
      if (!tagsArray.includes(tag)) {
        tagsArray.push(tag);
      }
    }
  }

  const addFilter = (tag) => {
    setCurrentFilter(tag);
  };

  return (
    <>
      <Head>
        <title>Version One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        <main className="flex flex-col w-full h-auto">
          <a
            target="_blank"
            href="https://simplesuite.co"
            className="fixed flex items-center px-4 space-x-2 transition duration-200 transform rounded-full h-11 bg-neutral-900 bottom-4 right-4 hover:scale-105 hover:opacity-90"
          >
            <img src="/img/small-logo.svg" />
            <span className="text-sm font-normal text-white font-inter">
              Get your MVP built
            </span>
          </a>
          <header className="w-full relative h-screen flex justify-center items-center bg-[#F5F2EE]">
            <motion.div
              initial={{ y: "-100%" }}
              animate={{ y: 0 }}
              transition={{ duration: 1 }}
              className="absolute flex items-center space-x-2 top-6"
            >
              <span className="text-xs font-normal lowercase font-inter text-neutral-500">
                a mini project by
              </span>
              <a
                target="_blank"
                href="https://simplesuite.co"
                className="hover:opacity-70"
              >
                <img src="/logo.svg" />
              </a>
            </motion.div>

            {/* Arrow Bottom */}
            <motion.div
              initial={{ y: 100 }}
              animate={{ y: 0 }}
              transition={{ duration: 1 }}
              className="absolute bottom-10"
            >
              <a href="#companies">
                <div className="w-4 transform rotate-180 hover:opacity-70">
                  <ArrowDrawing />
                </div>
              </a>
            </motion.div>

            <div className="flex flex-col w-full max-w-5xl">
              <h1 className="font-medium text-center text-black leading-tighter text-7xl font-garamond">
                "The thing I probably repeat most is this recipe for a startup:
                get a <span className="italic">version 1</span> out fast, then
                improve it based on users' reactions."
              </h1>
              <motion.div className="flex items-center justify-center w-full mt-6 space-x-2 text-lg font-normal font-garamond text-neutral-500">
                <a
                  className="hover:underline"
                  target="_blank"
                  href="http://www.paulgraham.com/index.html"
                >
                  Paul Graham
                </a>
                <span>·</span>
                <a
                  className="hover:underline"
                  target="_blank"
                  href="http://www.paulgraham.com/startuplessons.html"
                >
                  The Hardest Lessons for Startups to Learn
                </a>
              </motion.div>
            </div>
          </header>
          <section id="companies" className="flex justify-center w-full pt-20">
            <div className="flex flex-col w-full max-w-6xl">
              <div className="flex flex-col w-full">
                <h2 className="w-7/12 text-6xl font-medium text-black font-garamond">
                  A reminder that everyone started from somewhere.
                </h2>
                <p className="mt-4 font-sans text-lg font-light text-neutral-500">
                  A directory of successful companies and the first version of
                  their product & website.
                </p>
              </div>
              <div className="flex flex-wrap w-full -ml-2 mt-14">
                {tagsArray.map((tag) => (
                  <Tag
                    tag={tag}
                    addFilter={addFilter}
                    currentFilter={currentFilter}
                  />
                ))}
              </div>
              <div className="grid w-full grid-cols-3 pb-20 mt-8 gap-x-6 gap-y-12">
                {companies
                  .filter((i) => i.tags.includes(currentFilter))
                  .map((company) => (
                    <Card
                      name={company.name}
                      year={company.year}
                      url={company.url}
                      previewImg={company.previewImg}
                    />
                  ))}
              </div>
            </div>
          </section>
          <footer className="flex items-center justify-center w-full py-5">
            <span className="text-sm font-normal font-inter text-neutral-500">
              © Simple Suite Ventures Ltd. All rights reserved.
            </span>
          </footer>
        </main>
      </AnimatePresence>
    </>
  );
}
